In [1]:
import pandas as pd
import numpy as np

# creating a random dataset

study_hours = np.random.normal(10,2,1000)
sleeping_hours = np.random.normal(10,2,1000)

passed = (study_hours + np.random.normal(0,1,1000)) > (sleeping_hours + np.random.normal(0,1,1000))
passed = passed.astype(int)

In [2]:
df = pd.DataFrame({'study_hours': study_hours,"sleeping_hours": sleeping_hours, "passed" :passed})
df['passed'].value_counts()

1    505
0    495
Name: passed, dtype: int64

In [3]:
df

study_hours  sleeping_hours  passed
0       6.855147       11.142977       0
1       9.193242        9.882881       0
2       7.373687       11.031998       0
3       8.345619       10.609477       0
4      10.680423       12.194164       0
..           ...             ...     ...
995     8.788861       10.639109       0
996     9.936919        7.408727       1
997    11.041321        9.222014       1
998    12.913051       10.237838       1
999    12.649849       10.339035       1

[1000 rows x 3 columns]

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [5]:
x = df[['study_hours','sleeping_hours']]
y = df['passed']

x_train, x_test, y_train, y_test, = train_test_split(x,y,test_size= 0.2, random_state=20)

In [6]:
log_model = LogisticRegression()
log_model.fit(x_train,y_train)

LogisticRegression()

In [7]:
y_pred = log_model.predict(x_test)

In [8]:
y_pred

array([1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1])

In [15]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import classification_report

In [14]:
print("confusion matrix")
print(confusion_matrix(y_test,y_pred))
print("Accuracy :- ",accuracy_score(y_test,y_pred))
print("Precision :- ",precision_score(y_test,y_pred))
print("Recall :- ",recall_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

confusion matrix
[[86  8]
 [16 90]]
Accuracy :-  0.88
Precision :-  0.9183673469387755
Recall :-  0.8490566037735849


In [17]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.91      0.88        94
           1       0.92      0.85      0.88       106

    accuracy                           0.88       200
   macro avg       0.88      0.88      0.88       200
weighted avg       0.88      0.88      0.88       200



# SVM

In [21]:
from sklearn import datasets
import pandas as pd 
# Importing iris data

iris = datasets.load_iris()

In [26]:
df = pd.DataFrame(data =iris.data, columns = iris.feature_names )
df["species"] = iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     species  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

In [27]:
x = df.drop(['species'], axis = 1)
y = df['species']

x_train, x_test, y_train, y_test, = train_test_split(x,y,test_size= 0.1, random_state=50)

In [31]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [32]:
print("confusion matrix")
print(confusion_matrix(y_test,y_pred))

print(classification_report(y_test,y_pred))

confusion matrix
[[6 0 0]
 [0 4 0]
 [0 0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00         4
           2       1.00      1.00      1.00         5

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

